eureka:
  instance:
    prefer-ip-address: true
    #表示eureka client发送心跳给server端的频率。如果  在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    lease-renewal-interval-in-seconds: 5 #注册服务默认心跳时间为30秒，当一个服务器不可用，需要3个心跳才能让服务器和客户端的元数据相同。生产环境最好使用默认配置。
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    healthcheck:
      enable: true # 开启健康检查（依赖spring-boot-starter-actuator）
    service-url:
      defaultZone: http://eureka:eureka@120.79.90.129:2188/eureka
      #开启密码模式 http://${userName}:${password}@localhost:2180/eureka
    registry-fetch-interval-seconds: 10


server:
  port: 11080
spring:
  application:
    name: zipkin-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/study?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
zipkin:
  collector:
    rabbitmq: 127.0.0.1:5672
    username: rabbitmq
    password: rabbitmq
    queue: zipkin
  storage:
    type: mysql
#不需要认证
management:
  security:
    enabled: true


