server:
  port: 2189

spring:
  application:
     name: zuul-gateway

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #表示eureka client发送心跳给server端的频率。如果  在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    lease-renewal-interval-in-seconds: 5 #注册服务默认心跳时间为30秒，当一个服务器不可用，需要3个心跳才能让服务器和客户端的元数据相同。生产环境最好使用默认配置。
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
  client:
    healthcheck:
      enable: true # 开启健康检查（依赖spring-boot-starter-actuator）
    service-url:
      defaultZone: http://eureka:eureka@localhost:2188/eureka
      #开启密码模式 http://${userName}:${password}@localhost:2180/eureka
    registry-fetch-interval-seconds: 10


security:
  #认证服务器
  auth:
    server: http://localhost:2190
#是否需要校验验证码
  capcha: false
#  user:
#    password: user  # 直接登录时的密码
#    ignored: /
#    sessions: never   # session策略
#    oauth2:
#      sso:
#        loginPath: /login   # 登录路径
#      client:
#        clientId: testclientId
#        clientSecret: testclientSecret
#        accessTokenUri: https://github.com/login/oauth/access_token
#        userAuthorizationUri: https://github.com/login/oauth/authorize
#      resource:
#        userInfoUri: https://api.github.com/user
#        preferTokenInfo: false
  sessions: stateless
  oauth2:
    client:
      clientId: com.wmang.spring.cloud.exercise
      clientSecret: com.wmang.spring.cloud.exercise.888888
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token #由资源服务器用来解码访问令牌
      service-id: zuul-gateway
      jwt:
         #key-uri: ${security.auth.server}/oauth/token_key #使用JWT令牌，RSA公开密钥可以用于令牌验证
         key-value: wmangccc.888888
#security:
#  validate:
#    code: false
#  sessions: stateless
#  oauth2:
#    resource:
#      loadBalanced: true
#      user-info-uri: http://system-auth-server/user
#      prefer-token-info: false
#      service-id: system-gateway-server
# 上述做法将权限认证和网关解耦、建议采用RSA加密验证方式

urls:
  collects:
  - /mobile/**
  - /auth/**
  - /admin/code/*
  - /admin/api/info
  - /admin/api/userTree
  - /admin/api/dictType/*
  - /swagger-resources/**
  - /swagger-ui.html
  - /*/v2/api-docs
  - /swagger/api-docs
  - /webjars/**



zuulFilter:
  permissionFilter: true
  errorFilter: true
  loggerFilter: true
  rules:
    whiteurl: /authentic-service/login,/test


zuul:
  ribbon:
    eager-load:
      enabled: true #开启Ribbon的饥饿加载模式
      clients: authentic-service,user-service #指定需要饥饿加载的客户端名称、服务名
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    authentic-service:
      path: /auth/**
      serviceId: authentic-service
      stripPrefix: true
      sensitiveHeaders:
    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: true
      sensitiveHeaders:
#    business-admin-server:
#      path: /admin/**
#      serviceId: business-admin-server
#      stripPrefix: true
#      sensitiveHeaders:
#    business-pay-server:
#      path: /pay/**
#      serviceId: business-pay-server
#      stripPrefix: true
#      sensitiveHeaders:
  ratelimit:
    key-prefix: business-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      user-service:
        limit: 100
        quota: 100
        refresh-interval: 3 #3秒内允许300个访问，平均每个请求2秒，并且要求总请求时间小于2400秒


#####################################################################################################
# redis配置
redis:
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password: redis***
  jedis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  # 连接超时时间（毫秒）
  timeout: 1000

#################redis哨兵设置#################
# Redis服务器master的名字
#  sentinel:
#    master: master8026
#    # redis-sentinel的配置地址和端口
#    nodes: 10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378
#####################################################################################################


#####################################################################################################

# 打印日志 trace
#logging:
#  level:
#    root: info
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.springms: DEBUG
##自定义日志格式
logging:
  config: classpath:logback.xml
#####################################################################################################

#动态刷新配置
#management:
#  endpoint:
#    us-refresh:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

##动态刷新配置文件
management:
  endpoints:
    web:
      exposure:
        #暴露bus-refresh节点，通过此节点刷新配置
        inclouds: '*'